### ISSUE TITLE
Create Milestones to organize issues

### ISSUE THREAD

**Issue by brinkbrink** [SeattleColleges/belindas-closet#19]
As a project manager, I will want to create milestones to organize issues.

**Is your feature request related to a problem? Please describe.**
We need a way to let developers divide assigned tasks into issues that make sense for pull requests and status updates. 

**Describe the solution you'd like**
We would like to create GH Milestones to give developers a starting point to create issues as they see fit.

**Describe alternatives you've considered**
We've considered assigning broad issues that developers can break up into smaller issues but that seems redundant and possibly not well organized.

**Additional context**
n/a

**Story Points**
1-3 story points

**Comment by taylorpapke** [comment]
This issue is outdated since we've moved to our new user story format.
