### ISSUE TITLE
Bug - Update issue templates

### ISSUE THREAD

**Issue by brinkbrink** [SeattleColleges/belindas-closet#47]
**Describe the bug**
We need to edit our existing issue templates and possibly add one for user stories because currently the directions in the feature request template are somewhat outdated, specifically with regards to title naming conventions.

**Expected behavior**
Edit the existing template and/or add a user story template and include current title convention:
USER STORY : < user story > 
< user story > : < issue name >

**Story Points**
1-4

**Comment by taylorpapke** [comment]
This is showing up in nsc-events Kansan. Closing this and creating a new issue for nsc-events.
